---
- hosts: all
  become: true
  tasks:

  - name: Install updates ( CENTOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: myrockys
  become: true
  tasks:
    - name: Install Web Server Package
      tags: httpd,centos
      dnf:
          name: httpd
          state: latest
    - name: copy default html file to site
      tags: httpd
      copy:
        src: /home/saifon/MyFirstRepo/file/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
